/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Bundle = IDL.Record({
  'id' : IDL.Text,
  'priceAmount' : IDL.Nat,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const InviteStatusType = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'granted' : IDL.Null,
  'usernameIncorrect' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'requiresInvite' : IDL.Bool,
  'title' : IDL.Text,
  'priceAmount' : IDL.Nat,
  'codePreview' : IDL.Text,
  'slug' : IDL.Text,
  'isFree' : IDL.Bool,
  'isPaid' : IDL.Bool,
  'instructions' : IDL.Text,
  'shortDescription' : IDL.Text,
  'hasScreenshots' : IDL.Bool,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'disclaimer' : IDL.Text,
  'downloadableFile' : IDL.Opt(ExternalBlob),
  'longDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'tradingViewUsername' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const InviteStatus = IDL.Record({
  'status' : InviteStatusType,
  'username' : IDL.Text,
  'productId' : IDL.Text,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrap' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createBundle' : IDL.Func([Bundle], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInviteStatus' : IDL.Func(
      [IDL.Text, InviteStatusType, IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteBundle' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBundle' : IDL.Func([IDL.Text], [Bundle], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartTotal' : IDL.Func([IDL.Vec(CartItem)], [IDL.Nat], ['query']),
  'getCartTotalWithShipping' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Nat],
      [IDL.Nat],
      ['query'],
    ),
  'getInviteStatuses' : IDL.Func([], [IDL.Vec(InviteStatus)], ['query']),
  'getMyInviteStatuses' : IDL.Func([], [IDL.Vec(InviteStatus)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductPriceAmount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBundle' : IDL.Func([Bundle], [], []),
  'updateInviteStatus' : IDL.Func(
      [IDL.Text, InviteStatusType, IDL.Text, IDL.Text, IDL.Principal],
      [],
      [],
    ),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Text,
    'priceAmount' : IDL.Nat,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const InviteStatusType = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'granted' : IDL.Null,
    'usernameIncorrect' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'requiresInvite' : IDL.Bool,
    'title' : IDL.Text,
    'priceAmount' : IDL.Nat,
    'codePreview' : IDL.Text,
    'slug' : IDL.Text,
    'isFree' : IDL.Bool,
    'isPaid' : IDL.Bool,
    'instructions' : IDL.Text,
    'shortDescription' : IDL.Text,
    'hasScreenshots' : IDL.Bool,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'disclaimer' : IDL.Text,
    'downloadableFile' : IDL.Opt(ExternalBlob),
    'longDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'tradingViewUsername' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const InviteStatus = IDL.Record({
    'status' : InviteStatusType,
    'username' : IDL.Text,
    'productId' : IDL.Text,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrap' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createBundle' : IDL.Func([Bundle], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInviteStatus' : IDL.Func(
        [IDL.Text, InviteStatusType, IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteBundle' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBundle' : IDL.Func([IDL.Text], [Bundle], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartTotal' : IDL.Func([IDL.Vec(CartItem)], [IDL.Nat], ['query']),
    'getCartTotalWithShipping' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Nat],
        [IDL.Nat],
        ['query'],
      ),
    'getInviteStatuses' : IDL.Func([], [IDL.Vec(InviteStatus)], ['query']),
    'getMyInviteStatuses' : IDL.Func([], [IDL.Vec(InviteStatus)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductPriceAmount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBundle' : IDL.Func([Bundle], [], []),
    'updateInviteStatus' : IDL.Func(
        [IDL.Text, InviteStatusType, IDL.Text, IDL.Text, IDL.Principal],
        [],
        [],
      ),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };