/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bundle {
  'id' : string,
  'priceAmount' : bigint,
  'productIds' : Array<string>,
  'name' : string,
  'description' : string,
  'currency' : string,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface InviteStatus {
  'status' : InviteStatusType,
  'username' : string,
  'productId' : string,
  'orderId' : string,
  'timestamp' : bigint,
  'buyer' : Principal,
}
export type InviteStatusType = { 'expired' : null } |
  { 'pending' : null } |
  { 'granted' : null } |
  { 'usernameIncorrect' : null };
export interface Product {
  'id' : string,
  'requiresInvite' : boolean,
  'title' : string,
  'priceAmount' : bigint,
  'codePreview' : string,
  'slug' : string,
  'isFree' : boolean,
  'isPaid' : boolean,
  'instructions' : string,
  'shortDescription' : string,
  'hasScreenshots' : boolean,
  'currency' : string,
  'category' : string,
  'disclaimer' : string,
  'downloadableFile' : [] | [ExternalBlob],
  'longDescription' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'tradingViewUsername' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBundle' : ActorMethod<[Bundle], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInviteStatus' : ActorMethod<
    [string, InviteStatusType, string, string, Principal],
    undefined
  >,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteBundle' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllBundles' : ActorMethod<[], Array<Bundle>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBundle' : ActorMethod<[string], Bundle>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartTotal' : ActorMethod<[Array<CartItem>], bigint>,
  'getCartTotalWithShipping' : ActorMethod<[Array<CartItem>, bigint], bigint>,
  'getInviteStatuses' : ActorMethod<[], Array<InviteStatus>>,
  'getMyInviteStatuses' : ActorMethod<[], Array<InviteStatus>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductPriceAmount' : ActorMethod<[string], bigint>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBundle' : ActorMethod<[Bundle], undefined>,
  'updateInviteStatus' : ActorMethod<
    [string, InviteStatusType, string, string, Principal],
    undefined
  >,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];